homepage/views.py

Avoid errors when client has no operating system information.

Handle missing HTTP_USER_AGENT.

---

homepage/templates/download_addons_win.html
homepage/templates/download_windows.html
homepage/templates/orange3.html
homepage/templatetags/tag_extras.py
orange_web/settings.py
orange_web/settings_production.py

Orange3 Windows installer link

---

homepage/templates/contributing-to-orange.html
homepage/views.py

Fix contact mail, address, unicode encoding.

Fix contact mail.

---

homepage/templates/base.html
homepage/templates/community.html
homepage/templates/contact.html

@BlazZupan, @janezd should want to review this.

Update contact page: stress orange tag, promote StackExchange

---

homepage/templates/base.html
homepage/templates/privacy_policy.html
homepage/views.py
orange_web/urls.py

An extra page with privacy policy information. Links from main page.

Privacy policy page

---

homepage/templates/features/education-in-data-science.html

Ema's revision of Edu text for website.

Revised text for Education in Data Science

---

homepage/static/css/custom.css
homepage/templates/download.html
homepage/templates/screenshots.html

Sorry because I am late. I haven't have enough time on my way and also internet connection was bad.

New template for screenshots.

---

homepage/static/widgets-associate.json
homepage/static/widgets-bioinformatics.json
homepage/static/widgets-datafusion.json
homepage/static/widgets-educational.json
homepage/static/widgets-network.json
homepage/static/widgets-text.json
homepage/templates/toolbox.html

Removed text above widget list.
QuickSelect now in focus.
Add-ons now in toolbox list.

Toolbox rehaul

---

homepage/static/css/custom.css
homepage/static/css/styles.css
homepage/templates/base.html
homepage/templates/citation.html
homepage/templates/community.html
homepage/templates/contact.html
homepage/templates/contributing-to-orange.html
homepage/templates/docs.html
homepage/templates/download.html
homepage/templates/feature_panel.html
homepage/templates/features/education-in-data-science.html
homepage/templates/features/interactive-data-visualization.html
homepage/templates/features/visual-programming.html
homepage/templates/homepage.html
homepage/templates/license.html
homepage/templates/privacy_policy.html
homepage/templates/screenshots.html
homepage/templates/start.html
homepage/templates/toolbox.html
homepage/views.py

Essential (!) SEO improvements!

Make feature titles linked to subpages

---

error_report/management/commands/manual_import.py
error_report/sentry.py
error_report/views.py
orange_web/settings.py
orange_web/settings_production.py

The PR includes the following enhancements for error sending to Sentry:
* Send a list of installed packages (aka pip freeze).
* Send a link to the Orange's schema if provided.
* For addons replace `release` with addon version and store orange version as `orange_version` tag.
* Support sending addon reports to different Sentry projects (different DSNs). If we cannot decide between addon vs core DSN from the stacktrace report is sent to both and marked with a tag `duplicated_in_addon`/`duplicated_in_core`.
* Add logging on production.

[ENH] ErrorReport: Pip Freeze, Addons Info, Multiple DSNs

---

download/filenames.set
download/filenames_mac.set
homepage/templates/download.html
homepage/templates/homepage.html
homepage/templatetags/tag_extras.py
homepage/views.py

Show version on Download page

---

homepage/templates/base.html

Added Google Tag Manager for page analytics.

Google Tag Manager

---

error_report/sentry.py
orange_web/settings_production.py

Sentry: add geo, datasets, and conformal

Sentry: add geo, datasets, and conformal

---

courses/templates/courses/text-analysis.html

Added info on scholarship options.

Add scholarship info

---

error_report/sentry.py

Sentry: add lekbf & fix testing

Sentry: add lekbf & fix testing

---

error_report/sentry.py

Sentry: add Infrared and 3rd Party addons

Sentry: add Infrared and 3rd Party addons

---

download/filenames.set
download/templates/download/windows.html
download/views.py

Replace the hardcoded link/filename with one that is read from a file.

Display link for the latest miniconda based installer

---

courses/templates/courses/digital-humanities-2017.html
courses/urls.py

Website with installation instructions for DH 2017 workshop.

Installation Instructions

---

homepage/static/css/custom.css
homepage/templates/base.html
wordpress_theme/orange-web-theme-child/inc/template-tags.php
wordpress_theme/orange-web-theme-child/style.css

- changed the style of a donate button in homepage/static/css/custom.css
- changed button tag to link with button style in homepage/templates/base.html
- changed wordpress_theme/orange-web-theme-child/inc/template-tags.php which allow adding css classes in wordpress menu and
added style for a donate button in wordpress_theme/orange-web-theme-child/style.css

Donate button

---

homepage/static/css/custom.css
homepage/templates/base.html
wordpress_theme/orange-web-theme-child/style.css

Style improvements: 
- hover
- open in a new tab.

Improve the style of donate button

---

error_report/sentry.py

Now textable errors are sent to Textable sentry.

Sentry: DSN textable

---

error_report/sentry.py

Error Reporting: add single cell

---

error_report/sentry.py

Error Reporting:  add new 3rd party

---

error_report/sentry.py

Error Reporting: add monroe-anal

Error Reporting: add monroe-anal

---

error_report/sentry.py

[FIX] Error Reporting: sentry associate DSN

---

error_report/sentry.py

Error Reporting: add spectroscopy

[FIX] Error Reporting: add spectroscopy

---

error_report/sentry.py

Error Reporting: add chemoinformatics

[FIX] Error Reporting: add chemoinformatics

---

orange_web/settings.py

Contact email was changed to avoid problems with Django send_mail and SMTP redirection.

Contact request workaround.

---

homepage/templates/data-mining-for-business.html
homepage/templates/introduction-to-data-mining.html
homepage/templates/text-mining-for-social-sciences.html

Important information, such as the nature of the data science classes offered, should be easily evident right after the title.
Thoughts?
Requested by @ajdapretnar.

Training: clarified on-request nature of classes

---

homepage/static/widgets-bioinformatics.json
homepage/static/widgets-image-analytics.json
homepage/static/widgets-text.json

Update the outdated widget catalogue.

Update widget catalogue

---

download/views.py

Move all exe and dmg files to a separate subdomain.

Update download links for installation files.
